### ISSUE TITLE
failures during testing with elderly numpy 1:1.5.1-1ubuntu2: AttributeError: 'memmap' object has no attribute 'filename'

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipy#259]
on ubuntu 11.04

```
======================================================================
ERROR: nipy.modalities.fmri.tests.test_glm.test_high_level_glm_with_paths
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/nipy-0.3.0/debian/tmp/usr/lib/python2.7/dist-packages/nipy/modalities/fmri/tests/test_glm.py", line 58, in test_high_level_glm_with_paths
    assert_true(z_image.get_data().std() < 3.)
  File "/usr/lib/pymodules/python2.7/numpy/core/memmap.py", line 257, in __array_finalize__
    self.filename = obj.filename
AttributeError: 'memmap' object has no attribute 'filename'

======================================================================
ERROR: nipy.modalities.fmri.tests.test_glm.test_high_level_glm_with_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/nipy-0.3.0/debian/tmp/usr/lib/python2.7/dist-packages/nipy/modalities/fmri/tests/test_glm.py", line 93, in test_high_level_glm_with_data
    assert_true(z_image.get_data().std() < 3. )
  File "/usr/lib/pymodules/python2.7/numpy/core/memmap.py", line 257, in __array_finalize__
    self.filename = obj.filename
AttributeError: 'memmap' object has no attribute 'filename'

----------------------------------------------------------------------

```

**Comment by effigies** [comment]
I think we can call this one stale.
