### ISSUE TITLE
Intermittent memory error in `test_parcel_analysis_spm`

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipy#358]
In latest travis test run - a memory error for one run in the matrix:

```
======================================================================
ERROR: nipy.algorithms.group.tests.test_parcel_analysis.test_parcel_analysis_spm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/tests/test_parcel_analysis.py", line 80, in test_parcel_analysis_spm
    _test_parcel_analysis('spm', None)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/tests/test_parcel_analysis.py", line 53, in _test_parcel_analysis
    parcel_info=parcel_info)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/parcel_analysis.py", line 274, in __init__
    self._smooth_images(write_smoothed_images)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/parcel_analysis.py", line 291, in _smooth_images
    method=self.smooth_method)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/parcel_analysis.py", line 118, in _smooth_image_pair
    scon, svcon = smooth_fn(con, vcon, msk, sigma)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/parcel_analysis.py", line 92, in _smooth_spm
    K = _gaussian_energy(sigma)
  File "/home/travis/build/matthew-brett/nipy/venv/lib/python3.4/site-packages/nipy/algorithms/group/parcel_analysis.py", line 63, in _gaussian_energy
    x = np.zeros(mask_size)
MemoryError
```

See: https://travis-ci.org/matthew-brett/nipy/jobs/78490793

Testing of same commit a little earlier had given no memory error : https://travis-ci.org/matthew-brett/nipy/builds/78460738

Related to random numbers used in tests?

**Comment by matthew-brett** [comment]
Another example : http://nipy.bic.berkeley.edu/builders/nipy-bdist32-27/builds/63/steps/shell_8/logs/stdio

**Comment by matthew-brett** [comment]
I'm guessing that intermittent (but fairly frequent) random stalls on travis are for the same reason:

https://travis-ci.org/nipy/nipy/jobs/82215378

@alexis-roche - would you mind having a look?  I'm sure it can be swept under the carpet by setting a seed, but it is worrying that the algorithm is fragile, the problem doesn't look very large.

**Comment by matthew-brett** [comment]
It looks like my guess was right - the frequent travis failures come from `test_parcel_analysis_spm`:

https://travis-ci.org/nipy/nipy/jobs/82591872

**Comment by matthew-brett** [comment]
Alexis - sorry to ask - last problem I think - but would you mind having a look at this one?  The test failures are fairly common, maybe one every 10 test runs, and that makes it difficult to use the travis and buildbots easily, because I have to keep checking logs to see whether there's a real failure.
