### ISSUE TITLE
ValueError in examples/labs/need_data/localizer_glm_ar.py

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipy#370]
I think automated tests have found an error in this example.  Here's the log (line endings lost, sorry).  Bertrand - would you mind checking this example? 

```
Traceback (most recent call last): File "", line 1, in File "", line 141, in File "/Users/buildslave/osx-10.6/nipy-examples-3_4/build/venv/lib/python3.4/site-packages/nipy/modalities/fmri/glm.py", line 583, in contrast contrast_ = glm.contrast(con, contrast_type) File "/Users/buildslave/osx-10.6/nipy-examples-3_4/build/venv/lib/python3.4/site-packages/nipy/modalities/fmri/glm.py", line 236, in contrast resl = self.results_[l].Fcontrast(con_val) File "/Users/buildslave/osx-10.6/nipy-examples-3_4/build/venv/lib/python3.4/site-packages/nipy/algorithms/statistics/models/model.py", line 307, in Fcontrast matrix.shape[1])) ValueError: F contrasts should have shape[1] P=24, but this has shape[1] 25
```

http://nipy.bic.berkeley.edu/nipy-examples-3.4/labs-need_data-localizer_glm_ar.py.stderr

**Comment by matthew-brett** [comment]
Closed by #373
