### ISSUE TITLE
nipy.algorithms.statistics.models.tests.test_olsR: Arrays are not almost equal to 6 decimals

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/nipy#380]
```python
======================================================================
FAIL: nipy.algorithms.statistics.models.tests.test_olsR.test_results(11.593140668998998, 11.593140144949302, 6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 510, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 6 decimals
 ACTUAL: 11.593140668998998
 DESIRED: 11.593140144949302
>>  raise AssertionError(_build_err_msg())
```

**Comment by ignatenkobrain** [comment]
https://github.com/numpy/numpy/issues/5200

**Comment by matthew-brett** [comment]
I think this is closed by https://github.com/nipy/nipy/pull/381
