### ISSUE TITLE
[32bit] nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_mu2tet: AssertionError

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/nipy#382]
``` python
======================================================================
FAIL: nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_mu2tet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-i686-2.7/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 154, in test_mu2tet
    assert_equal(intvol.mu2_tet(0,0,0,0,1,0,0,1,0,1), (3./2 + np.sqrt(3./4))/2)
AssertionError: 1.1830127018922194 != 1.1830127018922192
----------------------------------------------------------------------
```

**Comment by matthew-brett** [comment]
Oops - sorry - I only just noticed this report.   Here's a fix : #403 - would you mind having a look?

**Comment by matthew-brett** [comment]
@ignatenkobrain - can you confirm that latest master fixes this bug?   Close issue if so?

**Comment by keszybz** [comment]
Yep, it's fixed [https://koji.fedoraproject.org/koji/taskinfo?taskID=17819353]. Thanks!
