### ISSUE TITLE
FmriRealign4d assumes horizontal slices

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipy#383]
Hi, I am pretty sure this is a nipy bug:

I have a 4d NIfTI file which has the following header (as seen via fslhd):

```
filename       /mnt/data9/NIdata/ofM.dr/FSL_GLM_work/GLM/_measurement_id_20151103_144306_4008_1_1/BET/9_brain.nii.gz

sizeof_hdr     348
data_type      FLOAT32
dim0           4
dim1           64
dim2           32
dim3           14
dim4           1440
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       16
nbyper         4
bitpix         32
pixdim0        0.000000
pixdim1        3.125000
pixdim2        2.812500
pixdim3        5.000000
pixdim4        1.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name   
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      3.124805  -0.030966  0.009274  -101.159325
qto_xyz:2      -0.009208  -0.281265  4.974913  -41.574932
qto_xyz:3      -0.033655  -2.798229  -0.500157  49.397179
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Superior-to-Inferior
qform_zorient  Posterior-to-Anterior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      3.124805  -0.030966  0.009274  -101.159325
sto_xyz:2      -0.009208  -0.281265  4.974913  -41.574932
sto_xyz:3      -0.033655  -2.798229  -0.500158  49.397179
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Left-to-Right
sform_yorient  Superior-to-Inferior
sform_zorient  Posterior-to-Anterior
file_type      NIFTI-1+
file_code      1
descrip        FSL5.0
aux_file       
```

When I try to use FmriRealign4d on it as part of my workflow, I get the following crash report:

```
File: crash-20151110-172457-chymera-realign.a00.pklz
Node: FSL_GLM_work.GLM.realign.a00
Working directory: /home/chymera/NIdata/ofM.dr/FSL_GLM_work/GLM/_measurement_id_20151103_144306_4008_1_1/realign


Node inputs:

between_loops = [5]
ignore_exception = False
in_file = ['/mnt/data9/NIdata/ofM.dr/FSL_GLM_work/GLM/_measurement_id_20151103_144306_4008_1_1/BET/9_brain.nii.gz']
loops = [5]
slice_order = [0, 2, 4, 6, 8, 10, 12, 1, 3, 5, 7, 9, 11, 13]
speedup = [5]
start = 0.0
time_interp = True
tr = 1.0
tr_slices = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1538, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1664, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 983, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/preprocess.py", line 166, in _run_interface
    speedup=list(self.inputs.speedup))
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/groupwise_registration.py", line 736, in estimate
    refscan=refscan)
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/groupwise_registration.py", line 631, in realign4d
    refscan=refscan) for run in runs]
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/groupwise_registration.py", line 550, in single_run_realign4d
    subsampling = adjust_subsampling(speedup_, im4d.get_shape()[0:3])
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/groupwise_registration.py", line 134, in get_shape
    self._load_data()
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/groupwise_registration.py", line 125, in _load_data
    self._init_timing_parameters()
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/groupwise_registration.py", line 163, in _init_timing_parameters
    "Provided slice_order: %s" % (nslices, self._slice_order))
ValueError: Incorrect slice indexes were provided. There are 32 slices in the volume, indexes should start from 0 and list all slices. Provided slice_order: [0, 2, 4, 6, 8, 10, 12, 1, 3, 5, 7, 9, 11, 13]
Interface FmriRealign4d failed to run. 
```

I understand that in humans slices are usually horizontal, but in most other species they are coronal. I think you should add an argument that allows overriding the default horizontal slice orientation. Actually, if you can point me to where the slice orientation is set, I could even try to do this myself - sadly, I was not able to follow the code to any point where slice orientation selection became obvious.

**Comment by satra** [comment]
@TheChymera - you may want to use the newer version SpaceTimeRealign which allows you to specify which dimension is the slice axis.

**Comment by TheChymera** [comment]
That solved the issue for me, but I still maintain that the above is real, and it sould either be fied, or `FmriRealign4d` should be deprecated.
