### ISSUE TITLE
Don't use matplotlib in a GUI-dependent fashion

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipy#414]
```
Traceback (most recent call last):
  File "preprocessing.py", line 20, in <module>
    from nipype.interfaces.nipy import SpaceTimeRealigner
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/__init__.py", line 4, in <module>
    from .utils import Similarity
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/utils.py", line 25, in <module>
    from nipy.algorithms.registration.histogram_registration import HistogramRegistration
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py", line 18, in <module>
    from .scripting import space_time_realign, aff2euler
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/lib64/python2.7/site-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/lib64/python2.7/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/lib64/python2.7/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named Tkinter
```

On my headless data analysis servers, on which I do not need and have disabled GUI support, I get [this error](https://github.com/matplotlib/matplotlib/issues/7115) from nipype. It seems matplotlib's default behaviour here is to use tkinter (a GUI package) for plotting.

Since from what I can tell we only use `plt.show` in `tools/make_examples.py` I suggest prepending all other `matplotlib.pyplot` imports with:

```
import matplotlib
matplotlib.use('agg')
```

like [nipype does it](https://github.com/nipy/nipype/issues/1635#issuecomment-247228322).

What do you think?

**Comment by TheChymera** [comment]
@matthew-brett any ideas about this?

**Comment by matthew-brett** [comment]
Really sorry - could you say a bit more about which code you are running to cause the error?  The examples?  We do have a custom test runner `nipnost` that sets the backend, and an example runner somewhere that does the same thing.

**Comment by TheChymera** [comment]
Well, the example is basically just what it looks like:

I cannot import anything relating to `SpaceTimeRealigner`(though this also happens for Realign4d, and, I assume, other classes):

```
In [1]: from nipy.algorithms.registration import SpaceTimeRealigner
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b0a6711151a9> in <module>()
----> 1 from nipy.algorithms.registration import SpaceTimeRealigner

/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py in <module>()
     16                                      Realign4d, FmriRealign4d)
     17 
---> 18 from .scripting import space_time_realign, aff2euler
     19 
     20 from nipy.testing import Tester

/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py in <module>()
     20 
     21 if HAVE_MPL:
---> 22     import matplotlib.pyplot as plt
     23 
     24 from .groupwise_registration import SpaceTimeRealign

/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py in <module>()
      4 
      5 from matplotlib.externals import six
----> 6 from matplotlib.externals.six.moves import tkinter as Tk
      7 from matplotlib.externals.six.moves import tkinter_filedialog as FileDialog
      8 

/usr/lib64/python2.7/site-packages/matplotlib/externals/six.pyc in load_module(self, fullname)
    197         mod = self.__get_module(fullname)
    198         if isinstance(mod, MovedModule):
--> 199             mod = mod._resolve()
    200         else:
    201             mod.__loader__ = self

/usr/lib64/python2.7/site-packages/matplotlib/externals/six.pyc in _resolve(self)
    111 
    112     def _resolve(self):
--> 113         return _import_module(self.mod)
    114 
    115     def __getattr__(self, attr):

/usr/lib64/python2.7/site-packages/matplotlib/externals/six.pyc in _import_module(name)
     78 def _import_module(name):
     79     """Import module, returning the module after the last dot."""
---> 80     __import__(name)
     81     return sys.modules[name]
     82 

ImportError: No module named Tkinter
```

The example above happens when I use any code at all to import the nipype interfaces for said classes:

```
In [3]: from nipype.interfaces.nipy import SpaceTimeRealigner
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-1a9f7a50a2da> in <module>()
----> 1 from nipype.interfaces.nipy import SpaceTimeRealigner

/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/__init__.py in <module>()
      2 from .model import FitGLM, EstimateContrast
      3 from .preprocess import ComputeMask, FmriRealign4d, SpaceTimeRealigner
----> 4 from .utils import Similarity

/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/utils.py in <module>()
     23     have_nipy = False
     24 else:
---> 25     from nipy.algorithms.registration.histogram_registration import HistogramRegistration
     26     from nipy.algorithms.registration.affine import Affine
     27 

/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py in <module>()
     16                                      Realign4d, FmriRealign4d)
     17 
---> 18 from .scripting import space_time_realign, aff2euler
     19 
     20 from nipy.testing import Tester

/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py in <module>()
     20 
     21 if HAVE_MPL:
---> 22     import matplotlib.pyplot as plt
     23 
     24 from .groupwise_registration import SpaceTimeRealign

/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py in <module>()
      4 
      5 from matplotlib.externals import six
----> 6 from matplotlib.externals.six.moves import tkinter as Tk
      7 from matplotlib.externals.six.moves import tkinter_filedialog as FileDialog
      8 

/usr/lib64/python2.7/site-packages/matplotlib/externals/six.pyc in load_module(self, fullname)
    197         mod = self.__get_module(fullname)
    198         if isinstance(mod, MovedModule):
--> 199             mod = mod._resolve()
    200         else:
    201             mod.__loader__ = self

/usr/lib64/python2.7/site-packages/matplotlib/externals/six.pyc in _resolve(self)
    111 
    112     def _resolve(self):
--> 113         return _import_module(self.mod)
    114 
    115     def __getattr__(self, attr):

/usr/lib64/python2.7/site-packages/matplotlib/externals/six.pyc in _import_module(name)
     78 def _import_module(name):
     79     """Import module, returning the module after the last dot."""
---> 80     __import__(name)
     81     return sys.modules[name]
     82 

ImportError: No module named Tkinter
```

I might actually have broken this myself with the `SpaceTimeRealign` update (because this wasn't happening last week) - but I don't see how.

**Comment by TheChymera** [comment]
@matthew-brett can you help me out with this? I tested it with `=nipy-0.4.0` and it still happens. So it wasn't my last PR that caused this, but rather, I likely unknowingly had tkinter support before my latest update.

**Comment by matthew-brett** [comment]
Does #415 fix it?

**Comment by TheChymera** [comment]
@matthew-brett yes, this fixes it!
