### ISSUE TITLE
Intermittent test failures in test_imm_loglike_1D_k10

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipy#418]
I observed this failure:

```
======================================================================
FAIL: nipy.algorithms.clustering.tests.test_imm.test_imm_loglike_1D_k10
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/mb312/dev_trees/nipy/nipy/algorithms/clustering/tests/test_imm.py", line 86, in test_imm_loglike_1D_k10
    assert_true(np.absolute(theoretical_ll-empirical_ll)<0.25*dim)
AssertionError: False is not true
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')
```

Investigating: 

```
(Pdb) np.absolute(theoretical_ll-empirical_ll)
0.25215277379595946
(Pdb) dim
1
```

The test passed when I ran it again without change to the code.  Test sensitive to variation from random number input?

**Comment by bthirion** [comment]
Yes, the obvious fix is to use a more tolerat bound, e.g.  `.5 * dim` instead.

**Comment by matthew-brett** [comment]
Is the the right fix - or that bound too lax do you think?

**Comment by bthirion** [comment]
No, that should be OK.
