### ISSUE TITLE
"setup.py clean" requires too many dependencies and does too much unrelated work

### ISSUE THREAD

**Issue by mr-c** [nipy/nipy#465]
``` console
$ python3 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from setup_helpers import (generate_a_pyrex_source, get_comrec_build,
  File "/home/michael/src/nipy/setup_helpers.py", line 36, in <module>
    from numpy.distutils.misc_util import appendpath
ModuleNotFoundError: No module named 'numpy'
$ sudo apt install python3-numpy
[...]
$ python3 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    raise RuntimeError(ver_err_msg)
RuntimeError: We need package scipy, but not importable
$ sudo apt install python3-scipy
[...]
$ python3 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    raise RuntimeError(ver_err_msg)
RuntimeError: We need package nibabel, but not importable
$ sudo apt install python3-nibabel
[...]
$ python3 setup.py clean
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_lapack_info:
  libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_clapack_info:
  libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

flame_info:
  libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /usr/local/lib
  libraries tatlas,tatlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries tatlas,tatlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries lapack_atlas not found in /usr/local/lib
  libraries satlas,satlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries satlas,satlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /usr/local/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries lapack_atlas not found in /usr/local/lib
  libraries f77blas,cblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries f77blas,cblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu/atlas
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

lapack_info:
  FOUND:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = f77

blas_opt_info:
blas_mkl_info:
  libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_info:
  libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

atlas_3_10_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

atlas_3_10_blas_info:
  libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

atlas_blas_info:
  libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:1914: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
blas_info:
C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmph0n3s8is/tmp
creating /tmp/tmph0n3s8is/tmp/tmph0n3s8is
compile options: '-I/usr/local/include -I/usr/include -c'
x86_64-linux-gnu-gcc: /tmp/tmph0n3s8is/source.c
x86_64-linux-gnu-gcc -pthread /tmp/tmph0n3s8is/tmp/tmph0n3s8is/source.o -lblas -o /tmp/tmph0n3s8is/a.out
  FOUND:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c

  FOUND:
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include']

Building with (slow) Lapack lite distribution: set NIPY_EXTERNAL_LAPACK environment variable or use setup.cfg to enable link to optimized BLAS / LAPACK
LAPACK build options:
library_dirs: [] 
libraries: [] 
lapack_info: {'libraries': ['lapack', 'lapack', 'blas', 'blas'], 'library_dirs': ['/usr/lib/x86_64-linux-gnu'], 'language': 'c', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include']} 
running clean
```

**Comment by matthew-brett** [comment]
Hmm - yes - totally agree - but I think this is Numpy.distutils' fault - at least - that's where all the messages seem to be coming from.   I guess that we're picking up Numpy.distutils via monkey-patching of distutils.   On the other hand, it does seem reasonable to do the directory removals that we do in our own code : 

https://github.com/nipy/nipy/blob/master/setup_helpers.py#L132

Any suggestions?

**Comment by mr-c** [comment]
> Any suggestions?

You could surround the imports of 3rd party packages with `try`/`catch` blocks and issue a warning if the command chosen needs those; which `clean` does not.

**Comment by matthew-brett** [comment]
Sorry - I don't understand the suggestion.  Where exactly would the try / catch blocks go?

**Comment by mr-c** [comment]
> Sorry - I don't understand the suggestion. Where exactly would the try / catch blocks go?

Around the numpy, scipy, and nibabel imports

https://github.com/nipy/nipy/blob/d16d268938dcd5c15748ca051532c21f57cf8a22/setup.py#L20

**Comment by effigies** [comment]
setup.py is gone.
