### ISSUE TITLE
test failures with Python 3.9 and the experimental Debian package

### ISSUE THREAD

**Issue by mr-c** [nipy/nipy#466]
> FAILED (SKIP=6, errors=9, failures=1)
```
======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/design.py", line 20, in <module>
    from .hrf import glover
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/fmristat/api.py", line 3, in <module>
    from .hrf import canonical as delay_hrf
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/fmristat/hrf.py", line 21, in <module>
    from .. import hrf
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/fmristat/hrf.py", line 21, in <module>
    from .. import hrf
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 15, in <module>
    from ... import utils, hrf, design
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/fmristat/tests/test_hrf.py", line 11, in <module>
    from ... import hrf
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/tests/test_design.py", line 8, in <module>
    from ..design import (event_design, block_design, stack2designs, stack_designs,
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/design.py", line 20, in <module>
    from .hrf import glover
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/tests/test_hrf.py", line 12, in <module>
    from ..hrf import (
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
ERROR: Failure: TypeError (unsupported operand type(s) for *: 'GreaterThan' and 'Add')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/tests/test_utils.py", line 30, in <module>
    from .. import hrf
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 123, in <module>
    _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/hrf.py", line 106, in gamma_expr
    coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'

======================================================================
FAIL: Doctest: nipy.modalities.fmri.utils.convolve_functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nipy.modalities.fmri.utils.convolve_functions
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 494, in convolve_functions

----------------------------------------------------------------------
File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 533, in nipy.modalities.fmri.utils.convolve_functions
Failed example:
    f1 = (t > 0) * (t < 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest nipy.modalities.fmri.utils.convolve_functions[2]>", line 1, in <module>
        f1 = (t > 0) * (t < 1)
    TypeError: unsupported operand type(s) for *: 'StrictGreaterThan' and 'StrictLessThan'
----------------------------------------------------------------------
File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 538, in nipy.modalities.fmri.utils.convolve_functions
Failed example:
    tri = convolve_functions(f1, f1, [0, 2], [0, 2], 1.0e-3, name='conv')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest nipy.modalities.fmri.utils.convolve_functions[3]>", line 1, in <module>
        tri = convolve_functions(f1, f1, [0, 2], [0, 2], 1.0e-3, name='conv')
    NameError: name 'f1' is not defined
----------------------------------------------------------------------
File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 542, in nipy.modalities.fmri.utils.convolve_functions
Failed example:
    print(tri)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest nipy.modalities.fmri.utils.convolve_functions[4]>", line 1, in <module>
        print(tri)
    NameError: name 'tri' is not defined
----------------------------------------------------------------------
File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 547, in nipy.modalities.fmri.utils.convolve_functions
Failed example:
    ftri = lambdify(t, tri)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest nipy.modalities.fmri.utils.convolve_functions[5]>", line 1, in <module>
        ftri = lambdify(t, tri)
    NameError: name 'tri' is not defined
----------------------------------------------------------------------
File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 549, in nipy.modalities.fmri.utils.convolve_functions
Failed example:
    y = ftri(x)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest nipy.modalities.fmri.utils.convolve_functions[7]>", line 1, in <module>
        y = ftri(x)
    NameError: name 'ftri' is not defined
----------------------------------------------------------------------
File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/modalities/fmri/utils.py", line 552, in nipy.modalities.fmri.utils.convolve_functions
Failed example:
    x[np.argmax(y)]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest nipy.modalities.fmri.utils.convolve_functions[8]>", line 1, in <module>
        x[np.argmax(y)]
    NameError: name 'y' is not defined


----------------------------------------------------------------------
```

**Comment by mr-c** [comment]
Here's the full build log: https://gist.github.com/mr-c/52ca16a11d5f4e927be496bcf312b5ad

**Comment by mr-c** [comment]
FYI, while nipy version 0.4.2 is in the current Debian release, it won't be in the next Debian release unless this gets fixed before March, 2021.

**Comment by yarikoptic** [comment]
`TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'` and alike smell like sympy issue... sympy 1.7.1 was released Dec 12, 2020  ... test building nipy ATM

**Comment by yarikoptic** [comment]
an additional issue: https://github.com/nipy/nipy/issues/468

**Comment by yarikoptic** [comment]
sympy issues: bisected and reported/asking sympy -- https://github.com/sympy/sympy/issues/20981

**Comment by mr-c** [comment]
Thanks for #470 ! However two failures remain, so can this issue be re-opened?

```
======================================================================
FAIL: nipy.algorithms.tests.test_interpolator.test_interpolator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/autopkgtest.80RSz9/build.zUe/src/.pybuild/cpython3_3.9_nipy/build/nipy/algorithms/tests/test_interpolator.py", line 23, in test_interpolator
    assert_almost_equal(interp.evaluate([0, 0, 4]), arr[0, 0, -1])
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 579, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 1042, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 6.399999999999993
Max relative difference: 2.133333333333331
 x: array(-3.399999999999993)
 y: array(3)

======================================================================
FAIL: nipy.algorithms.tests.test_resample.test_resample_outvalue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/autopkgtest.80RSz9/build.zUe/src/.pybuild/cpython3_3.9_nipy/build/nipy/algorithms/tests/test_resample.py", line 206, in test_resample_outvalue
    assert_array_almost_equal(img2.get_data(), exp_arr)
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 1042, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 26 / 27 (96.3%)
Max absolute difference: 5.500000000000007
Max relative difference: 0.21153846153846181
 x: array([[[  8.  ,   9.25,  10.5 ],
        [ 11.75,  13.  ,  14.25],
        [ 15.5 ,  16.75,  18.  ]],...
 y: array([[[  9.,  10.,  11.],
        [ 12.,  13.,  14.],
        [ 15.,  16.,  17.]],...

----------------------------------------------------------------------
```

**Comment by yarikoptic** [comment]
I filled those separately : #468 #471 . They weren't there yet in the original description here

I am planning now to upload to Debian with those two skipped and yeah them down later

**Comment by mr-c** [comment]
@yarikoptic thanks! I've already disabled the failing tests in the Debian package https://salsa.debian.org/med-team/nipy/-/commit/916951e85b314e13a570a9fd7921b93cb02316d8
