### ISSUE TITLE
test_resample_outvalue fails on debian sid

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipy#471]
might be related to #468

```
======================================================================
FAIL: nipy.algorithms.tests.test_resample.test_resample_outvalue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/nipy-0.4.3~rc1/.pybuild/cpython3_3.9_nipy/build/nipy/algorithms/tests/test_resample.py", line 206, in test_resample_outvalue
    assert_array_almost_equal(img2.get_data(), exp_arr)
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 1042, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
  File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals
Mismatched elements: 26 / 27 (96.3%)
Max absolute difference: 5.500000000000007
Max relative difference: 0.21153846153846181
 x: array([[[  8.  ,   9.25,  10.5 ],
        [ 11.75,  13.  ,  14.25],
        [ 15.5 ,  16.75,  18.  ]],...
 y: array([[[  9.,  10.,  11.],
        [ 12.,  13.,  14.],
        [ 15.,  16.,  17.]],...
```

**Comment by yarikoptic** [comment]
FWIW also goes away with downgrade of scipy to 1.5.4-1+b1 from 1.6.0-2

**Comment by yarikoptic** [comment]
seems to be the same cause as of #468 so let's continue there
