### ISSUE TITLE
incompatibility between nipy-0.4.2 and numpy-1.20.1

### ISSUE THREAD

**Issue by jiavila** [nipy/nipy#483]
Using `pip install nipy`, numpy-1.20.1 gets installed.  After starting a session in python 3.8 and using `import nipy`, I get the error below. Using `pip install numpy==1.17.4` seems to resolve the issue.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jesusavila/opt/anaconda3/envs/test_nipy/lib/python3.8/site-packages/nipy/__init__.py", line 12, in <module>
    from nipy.testing import Tester
  File "/Users/jesusavila/opt/anaconda3/envs/test_nipy/lib/python3.8/site-packages/nipy/testing/__init__.py", line 44, in <module>
    from . import decorators as dec
  File "/Users/jesusavila/opt/anaconda3/envs/test_nipy/lib/python3.8/site-packages/nipy/testing/decorators.py", line 11, in <module>
    from numpy.testing.decorators import *
ModuleNotFoundError: No module named 'numpy.testing.decorators'
```

**Comment by jiavila** [comment]
This is the same as [this issue](https://github.com/nipy/nipy/issues/463), so closed it

**Comment by matthew-brett** [comment]
Aha - yes - we need to do a new release.  Let's do that.
