### ISSUE TITLE
nipy cannot work with nibabel>3.2

### ISSUE THREAD

**Issue by servoz** [nipy/nipy#555]
```
$ python
Python 3.9.9 (main, Nov 19 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nibabel
>>> nibabel.__version__
'5.2.0'
>>> import nipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.9/site-packages/nipy/__init__.py", line 32, in <module>
    from nipy.io.api import load_image, save_image, as_image
  File "/home/econdami/.local/lib/python3.9/site-packages/nipy/io/api.py", line 3, in <module>
    from .files import load as load_image, save as save_image, as_image
  File "/home/econdami/.local/lib/python3.9/site-packages/nipy/io/files.py", line 22, in <module>
    from ..core.image.image import is_image
  File "/home/econdami/.local/lib/python3.9/site-packages/nipy/core/image/__init__.py", line 13, in <module>
    from . import image
  File "/home/econdami/.local/lib/python3.9/site-packages/nipy/core/image/image.py", line 34, in <module>
    class Image(object):
  File "/home/econdami/.local/lib/python3.9/site-packages/nipy/core/image/image.py", line 84, in Image
    def shape(self):
  File "/home/econdami/.local/lib/python3.9/site-packages/nibabel/deprecator.py", line 208, in deprecated_func
    raise exception(message)
nibabel.deprecator.ExpiredDeprecationError: setattr_on_read has been renamed to auto_attr. Please use nibabel.onetime.auto_attr

* deprecated from version: 3.2
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
>>>
```
 
and

```
$ python
Python 3.9.9 (main, Nov 19 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nibabel
>>> nibabel.__version__
'3.2.2'
>>> import nipy
>>> 

```
Since nibabel==3.2, `setattr_on_read` has been renamed `auto_attr`.

The consequence is that if nibabel version is higher, an exception is thrown preventing the import of nipy.

I think there are at least two solutions:
- 1 put in the nipy dependencies: `nibabel<=3.2` (I don't think this is desirable)
- 2 replace `nibabel.onetime.setattr_on_read` with `nibabel.onetime.auto_attr` everywhere in nipy.

If you wish, I can make this change (solution 2) in a PR.

**Comment by effigies** [comment]
Please use the latest master. This has been addressed and is waiting on release.

**Comment by servoz** [comment]
Thank you for your prompt reply!
